// min8t-plugin-sdk/examples/react/Min8tEditor.tsx
/**
 * min8tEmail Plugin SDK - React Integration Component
 *
 * Production-ready React component demonstrating complete min8t plugin integration
 * with TypeScript, error boundaries, cleanup, and all plugin API methods.
 *
 * @packageDocumentation
 * @version 1.0.0
 * @author min8t Team
 * @license MIT
 *
 * **Features:**
 * - Full TypeScript typing with imported plugin SDK types
 * - Proper React 18 lifecycle management (useEffect cleanup)
 * - Error boundary integration for graceful error handling
 * - All plugin API methods demonstrated (init, getHtml, setHtml, save, export)
 * - Loading and error states
 * - Props-based configuration
 * - Production-ready patterns
 *
 * **Based on Research:**
 * - Plugin SDK API: /services/15_plugin_sdk_service/frontend/src/index.ts
 * - React best practices: https://react.dev/reference/react/useEffect
 * - Error boundaries: https://github.com/bvaughn/react-error-boundary
 * - TypeScript patterns: React TypeScript Cheatsheet
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';

/**
 * Import types from the min8t plugin SDK
 *
 * These types are generated from the UMD bundle and provide full TypeScript
 * support for the plugin API.
 */
import type {
  PluginConfig,
  PluginApiResponse,
  PluginSaveResponse,
  PluginExportResponse,
  ErrorResponse,
  Min8tPlugin
} from '../../dist/index.d';

/**
 * Extend the Window interface to include the min8t plugin
 *
 * This is necessary for TypeScript to recognize window.min8t
 */
declare global {
  interface Window {
    min8t: Min8tPlugin;
  }
}

/**
 * Props for the Min8tEditor component
 *
 * All required configuration is passed via props for maximum flexibility
 */
export interface Min8tEditorProps {
  /** Unique plugin identifier (from min8t dashboard) */
  pluginId: string;

  /** Email template identifier */
  emailId: string;

  /** Authentication token (ES-PLUGIN-AUTH format) */
  authToken: string;

  /** Locale/language code (default: 'en') */
  locale?: string;

  /** UI theme preference (default: 'light') */
  theme?: 'light' | 'dark';

  /** Base URL for the plugin API (optional, auto-detected if not provided) */
  baseUrl?: string;

  /** White-label customization options */
  customization?: {
    branding?: boolean;
    logoUrl?: string;
    primaryColor?: string;
    features?: string[];
  };

  /** Callback when template is saved successfully */
  onSave?: (result: PluginSaveResponse) => void;

  /** Callback when an error occurs */
  onError?: (error: ErrorResponse | Error) => void;

  /** Callback when plugin initialization completes */
  onInitialized?: () => void;

  /** Custom container class name */
  className?: string;

  /** Custom container styles */
  style?: React.CSSProperties;
}

/**
 * Min8tEditor Component
 *
 * Production-ready React component that embeds the min8t email editor.
 *
 * @example
 * ```tsx
 * <Min8tEditor
 *   pluginId="min8t_pk_your_plugin_id"
 *   emailId="email-456"
 *   authToken="your-es-plugin-auth-token"
 *   locale="en"
 *   theme="light"
 *   onSave={(result) => console.log('Saved:', result)}
 *   onError={(error) => console.error('Error:', error)}
 * />
 * ```
 */
export const Min8tEditor: React.FC<Min8tEditorProps> = ({
  pluginId,
  emailId,
  authToken,
  locale = 'en',
  theme = 'light',
  baseUrl,
  customization,
  onSave,
  onError,
  onInitialized,
  className,
  style
}) => {
  // Ref to the container DOM element
  const containerRef = useRef<HTMLDivElement>(null);

  // State management
  const [isLoading, setIsLoading] = useState(true);
  const [isInitialized, setIsInitialized] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Handle plugin initialization errors
   *
   * This wraps errors in a consistent format and calls the onError callback
   */
  const handleError = useCallback((err: ErrorResponse | Error, context: string) => {
    console.error(`[Min8tEditor] ${context}:`, err);

    const errorMessage = err instanceof Error
      ? err.message
      : err.error || 'Unknown error';

    setError(errorMessage);
    setIsLoading(false);

    if (onError) {
      onError(err);
    }
  }, [onError]);

  /**
   * Initialize the min8t plugin
   *
   * This effect runs once when the component mounts and handles:
   * 1. Plugin initialization via window.min8t.init()
   * 2. Error handling
   * 3. Cleanup on unmount (destroy plugin)
   *
   * React 18 best practice: Cleanup is symmetrical to setup
   */
  useEffect(() => {
    let isMounted = true;

    const initializePlugin = async () => {
      try {
        // Verify that the plugin script has loaded
        if (!window.min8t) {
          throw new Error(
            'min8t plugin not found. Ensure the plugin script is loaded before mounting this component.'
          );
        }

        // Build plugin configuration
        const config: PluginConfig = {
          pluginId,
          apiRequestData: {
            emailId
          },
          getAuthToken: () => authToken,
          locale,
          theme,
          baseUrl,
          customization
        };

        console.log('[Min8tEditor] Initializing plugin with config:', {
          pluginId,
          emailId,
          locale,
          theme
        });

        // Initialize the plugin
        await window.min8t.init(config);

        // Only update state if component is still mounted
        // This prevents "Can't perform a React state update on an unmounted component" warnings
        if (isMounted) {
          setIsInitialized(true);
          setIsLoading(false);
          console.log('[Min8tEditor] Plugin initialized successfully');

          if (onInitialized) {
            onInitialized();
          }
        }
      } catch (err: any) {
        if (isMounted) {
          handleError(err, 'Initialization failed');
        }
      }
    };

    initializePlugin();

    /**
     * Cleanup function (React 18 best practice)
     *
     * This runs when the component unmounts and ensures the plugin
     * is properly destroyed to prevent memory leaks.
     */
    return () => {
      isMounted = false;

      if (window.min8t && window.min8t.isInitialized()) {
        console.log('[Min8tEditor] Cleaning up plugin on unmount');
        window.min8t.destroy();
      }
    };
  }, [
    pluginId,
    emailId,
    authToken,
    locale,
    theme,
    baseUrl,
    customization,
    onInitialized,
    handleError
  ]);

  /**
   * Get current HTML and CSS from the editor
   *
   * Public method exposed via ref (see useImperativeHandle pattern below)
   */
  const getHtml = useCallback(async (): Promise<PluginApiResponse> => {
    if (!isInitialized) {
      throw new Error('Plugin not initialized');
    }

    try {
      const result = await window.min8t.getHtml();
      console.log('[Min8tEditor] Retrieved HTML/CSS:', {
        htmlLength: result.html.length,
        cssLength: result.css.length
      });
      return result;
    } catch (err: any) {
      handleError(err, 'getHtml() failed');
      throw err;
    }
  }, [isInitialized, handleError]);

  /**
   * Set HTML and CSS in the editor
   *
   * @param html - HTML content
   * @param css - CSS content
   */
  const setHtml = useCallback(async (html: string, css: string): Promise<void> => {
    if (!isInitialized) {
      throw new Error('Plugin not initialized');
    }

    try {
      await window.min8t.setHtml(html, css);
      console.log('[Min8tEditor] HTML/CSS set successfully');
    } catch (err: any) {
      handleError(err, 'setHtml() failed');
      throw err;
    }
  }, [isInitialized, handleError]);

  /**
   * Save the current template to the backend
   */
  const save = useCallback(async (): Promise<PluginSaveResponse> => {
    if (!isInitialized) {
      throw new Error('Plugin not initialized');
    }

    try {
      const result = await window.min8t.save();
      console.log('[Min8tEditor] Template saved successfully:', result);

      if (onSave) {
        onSave(result);
      }

      return result;
    } catch (err: any) {
      handleError(err, 'save() failed');
      throw err;
    }
  }, [isInitialized, onSave, handleError]);

  /**
   * Export the template in specified format
   *
   * @param format - Export format (html, zip, pdf)
   */
  const exportTemplate = useCallback(async (
    format: 'html' | 'zip' | 'pdf'
  ): Promise<PluginExportResponse> => {
    if (!isInitialized) {
      throw new Error('Plugin not initialized');
    }

    try {
      const result = await window.min8t.export(format);
      console.log('[Min8tEditor] Template exported successfully:', {
        format,
        downloadUrl: result.downloadUrl
      });
      return result;
    } catch (err: any) {
      handleError(err, `export(${format}) failed`);
      throw err;
    }
  }, [isInitialized, handleError]);

  /**
   * Render loading state
   */
  if (isLoading) {
    return (
      <div
        className={className}
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          height: '600px',
          ...style
        }}
      >
        <div style={{ textAlign: 'center' }}>
          <div
            style={{
              border: '4px solid #f3f3f3',
              borderTop: '4px solid #3498db',
              borderRadius: '50%',
              width: '40px',
              height: '40px',
              animation: 'spin 1s linear infinite',
              margin: '0 auto 16px'
            }}
          />
          <p style={{ color: '#666', margin: 0 }}>Loading min8t editor...</p>
        </div>
        <style>
          {`
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}
        </style>
      </div>
    );
  }

  /**
   * Render error state
   */
  if (error) {
    return (
      <div
        className={className}
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          height: '600px',
          ...style
        }}
      >
        <div
          style={{
            padding: '24px',
            backgroundColor: '#fee',
            border: '1px solid #fcc',
            borderRadius: '4px',
            maxWidth: '500px'
          }}
        >
          <h3 style={{ margin: '0 0 12px', color: '#c33' }}>
            Failed to load min8t editor
          </h3>
          <p style={{ margin: 0, color: '#666' }}>{error}</p>
        </div>
      </div>
    );
  }

  /**
   * Render the plugin container
   *
   * The plugin will inject an iframe into this container during initialization
   */
  return (
    <div
      ref={containerRef}
      id="min8t-plugin"
      className={className}
      style={{
        width: '100%',
        height: '600px',
        position: 'relative',
        ...style
      }}
    />
  );
};

/**
 * Create a custom hook to expose plugin methods to parent components
 *
 * This allows parent components to call plugin methods imperatively
 *
 * @example
 * ```tsx
 * const editorRef = useRef<Min8tEditorHandle>(null);
 *
 * const handleSave = async () => {
 *   if (editorRef.current) {
 *     await editorRef.current.save();
 *   }
 * };
 *
 * <Min8tEditor ref={editorRef} {...props} />
 * ```
 */
export interface Min8tEditorHandle {
  getHtml: () => Promise<PluginApiResponse>;
  setHtml: (html: string, css: string) => Promise<void>;
  save: () => Promise<PluginSaveResponse>;
  export: (format: 'html' | 'zip' | 'pdf') => Promise<PluginExportResponse>;
  isInitialized: () => boolean;
}

/**
 * Min8tEditor with forwardRef for imperative access
 *
 * This version allows parent components to call plugin methods directly
 */
export const Min8tEditorWithRef = React.forwardRef<
  Min8tEditorHandle,
  Min8tEditorProps
>((props, ref) => {
  const [isInitialized, setIsInitialized] = useState(false);

  // Expose plugin methods to parent component via ref
  React.useImperativeHandle(ref, () => ({
    getHtml: async () => {
      if (!window.min8t || !isInitialized) {
        throw new Error('Plugin not initialized');
      }
      return await window.min8t.getHtml();
    },
    setHtml: async (html: string, css: string) => {
      if (!window.min8t || !isInitialized) {
        throw new Error('Plugin not initialized');
      }
      await window.min8t.setHtml(html, css);
    },
    save: async () => {
      if (!window.min8t || !isInitialized) {
        throw new Error('Plugin not initialized');
      }
      return await window.min8t.save();
    },
    export: async (format: 'html' | 'zip' | 'pdf') => {
      if (!window.min8t || !isInitialized) {
        throw new Error('Plugin not initialized');
      }
      return await window.min8t.export(format);
    },
    isInitialized: () => isInitialized
  }), [isInitialized]);

  return (
    <Min8tEditor
      {...props}
      onInitialized={() => {
        setIsInitialized(true);
        if (props.onInitialized) {
          props.onInitialized();
        }
      }}
    />
  );
});

Min8tEditorWithRef.displayName = 'Min8tEditorWithRef';

export default Min8tEditor;

// min8t-plugin-sdk/examples/vue/Min8tEditor.vue
<template>
  <div class="min8t-editor-wrapper">
    <!-- Loading State -->
    <div v-if="loading" class="min8t-loading">
      <div class="spinner"></div>
      <p>Initializing min8t Email Editor...</p>
    </div>

    <!-- Error State -->
    <div v-if="error" class="min8t-error">
      <h3>Error Loading Editor</h3>
      <p>{{ error.message }}</p>
      <p v-if="error.details" class="error-details">{{ error.details }}</p>
      <button @click="retryInit" class="retry-button">Retry</button>
    </div>

    <!-- Editor Container -->
    <div
      v-show="!loading && !error"
      ref="editorContainer"
      id="min8t-plugin"
      class="min8t-editor-container"
    ></div>

    <!-- Action Buttons -->
    <div v-if="!loading && !error" class="min8t-actions">
      <button @click="handleSave" :disabled="saving" class="action-button save-button">
        {{ saving ? 'Saving...' : 'Save Template' }}
      </button>
      <button @click="handleGetHtml" class="action-button">Get HTML</button>
      <button @click="handleExport('html')" class="action-button">Export HTML</button>
      <button @click="handleExport('zip')" class="action-button">Export ZIP</button>
      <button @click="handleExport('pdf')" class="action-button">Export PDF</button>
    </div>

    <!-- HTML Preview (conditionally shown) -->
    <div v-if="htmlPreview" class="min8t-preview">
      <h3>Template HTML Preview</h3>
      <pre><code>{{ htmlPreview }}</code></pre>
      <button @click="htmlPreview = null" class="close-preview">Close Preview</button>
    </div>
  </div>
</template>

<script setup lang="ts">
/**
 * min8t Email Editor - Vue 3 Component
 *
 * Production-ready Vue 3 component demonstrating min8t Plugin SDK integration
 * using Composition API with <script setup> and TypeScript.
 *
 * @example
 * ```vue
 * <template>
 *   <Min8tEditor
 *     plugin-id="min8t_pk_your_plugin_id"
 *     email-id="email-456"
 *     auth-token="ES-PLUGIN-AUTH-TOKEN"
 *     locale="en"
 *     theme="light"
 *     @save="handleSave"
 *     @error="handleError"
 *   />
 * </template>
 *
 * <script setup>
 * import Min8tEditor from './Min8tEditor.vue'
 *
 * function handleSave(result) {
 *   console.log('Template saved:', result)
 * }
 *
 * function handleError(error) {
 *   console.error('Editor error:', error)
 * }
 * </script>
 * ```
 *
 * @packageDocumentation
 * @version 1.0.0
 * @author min8t Team
 * @license MIT
 */

import { ref, onMounted, onUnmounted, watch } from 'vue'
import type {
  Min8tPlugin,
  PluginConfig,
  PluginSaveResponse,
  PluginApiResponse,
  PluginExportResponse,
  ErrorResponse
} from '../../dist/index.d'

/**
 * Component Props Interface
 *
 * Defines all configurable properties for the min8t editor component.
 */
interface Props {
  /** Unique plugin identifier (from min8t dashboard) */
  pluginId: string

  /** Email template identifier */
  emailId: string

  /** ES-PLUGIN-AUTH authentication token */
  authToken: string

  /** Locale/language code (default: 'en') */
  locale?: string

  /** UI theme preference (default: 'light') */
  theme?: 'light' | 'dark'

  /** Base URL for the plugin API (optional, auto-detected) */
  baseUrl?: string

  /** White-label customization options */
  customization?: {
    branding?: boolean
    logoUrl?: string
    primaryColor?: string
    features?: string[]
  }
}

/**
 * Component Emits Interface
 *
 * Defines all events emitted by this component.
 */
interface Emits {
  /** Emitted when template is successfully saved */
  save: [result: PluginSaveResponse]

  /** Emitted when an error occurs */
  error: [error: ErrorResponse]

  /** Emitted when HTML is retrieved */
  'html-retrieved': [data: PluginApiResponse]

  /** Emitted when template is exported */
  export: [data: PluginExportResponse]

  /** Emitted when plugin is initialized */
  initialized: []

  /** Emitted when plugin is destroyed */
  destroyed: []
}

// Define component props with defaults
const props = withDefaults(defineProps<Props>(), {
  locale: 'en',
  theme: 'light',
  baseUrl: undefined,
  customization: undefined
})

// Define component emits
const emit = defineEmits<Emits>()

/**
 * ========================
 * REACTIVE STATE
 * ========================
 */

/** Reference to the editor container DOM element */
const editorContainer = ref<HTMLElement | null>(null)

/** Loading state during initialization */
const loading = ref<boolean>(true)

/** Error state if initialization fails */
const error = ref<ErrorResponse | null>(null)

/** Saving state during template save */
const saving = ref<boolean>(false)

/** HTML preview content (optional) */
const htmlPreview = ref<string | null>(null)

/** min8t plugin instance (from window.min8t) */
let pluginInstance: Min8tPlugin | null = null

/**
 * ========================
 * PLUGIN INITIALIZATION
 * ========================
 */

/**
 * Initialize the min8t plugin
 *
 * Called on component mount and when retry is clicked.
 */
async function initPlugin(): Promise<void> {
  try {
    loading.value = true
    error.value = null

    // Verify window.min8t is available
    if (typeof window === 'undefined' || !(window as any).min8t) {
      throw new Error(
        'min8t plugin SDK not loaded. Please include the script: ' +
        '<script src="https://plugins.min8t.com/static/latest/min8t.js"></script>'
      )
    }

    pluginInstance = (window as any).min8t as Min8tPlugin

    // Build plugin configuration
    const config: PluginConfig = {
      pluginId: props.pluginId,
      apiRequestData: {
        emailId: props.emailId
      },
      getAuthToken: () => props.authToken,
      locale: props.locale,
      theme: props.theme,
      baseUrl: props.baseUrl,
      customization: props.customization
    }

    // Initialize the plugin
    await pluginInstance.init(config)

    loading.value = false
    emit('initialized')

    console.log('[Min8tEditor] Plugin initialized successfully')
  } catch (err: any) {
    loading.value = false
    error.value = {
      error: err.message || 'Plugin initialization failed',
      details: err.details || err.stack,
      errorType: err.errorType || 'server',
      isRecoverable: err.isRecoverable ?? true
    }

    emit('error', error.value)

    console.error('[Min8tEditor] Initialization failed:', err)
  }
}

/**
 * Retry plugin initialization
 *
 * Called when user clicks "Retry" button after an error.
 */
function retryInit(): void {
  initPlugin()
}

/**
 * ========================
 * PLUGIN METHODS
 * ========================
 */

/**
 * Save the current template
 *
 * Calls plugin.save() and emits the result.
 */
async function handleSave(): Promise<void> {
  if (!pluginInstance) {
    console.error('[Min8tEditor] Plugin not initialized')
    return
  }

  try {
    saving.value = true

    const result = await pluginInstance.save()

    emit('save', result)

    console.log('[Min8tEditor] Template saved:', result)

    // Optional: Show success notification
    alert(`Template saved successfully at ${result.savedAt}`)
  } catch (err: any) {
    const errorResponse: ErrorResponse = {
      error: err.message || 'Save failed',
      details: err.details,
      errorType: err.errorType || 'server',
      isRecoverable: err.isRecoverable ?? true
    }

    emit('error', errorResponse)

    console.error('[Min8tEditor] Save failed:', err)

    alert(`Save failed: ${err.message}`)
  } finally {
    saving.value = false
  }
}

/**
 * Get current HTML/CSS from the editor
 *
 * Calls plugin.getHtml() and displays preview.
 */
async function handleGetHtml(): Promise<void> {
  if (!pluginInstance) {
    console.error('[Min8tEditor] Plugin not initialized')
    return
  }

  try {
    const data = await pluginInstance.getHtml()

    emit('html-retrieved', data)

    // Show preview
    htmlPreview.value = data.html

    console.log('[Min8tEditor] HTML retrieved:', data)
  } catch (err: any) {
    const errorResponse: ErrorResponse = {
      error: err.message || 'Get HTML failed',
      details: err.details,
      errorType: err.errorType || 'server',
      isRecoverable: err.isRecoverable ?? true
    }

    emit('error', errorResponse)

    console.error('[Min8tEditor] Get HTML failed:', err)

    alert(`Get HTML failed: ${err.message}`)
  }
}

/**
 * Export template to specified format
 *
 * @param format - Export format (html, zip, pdf)
 */
async function handleExport(format: 'html' | 'zip' | 'pdf'): Promise<void> {
  if (!pluginInstance) {
    console.error('[Min8tEditor] Plugin not initialized')
    return
  }

  try {
    const result = await pluginInstance.export(format)

    emit('export', result)

    console.log(`[Min8tEditor] Template exported as ${format}:`, result)

    // Open download URL in new tab
    window.open(result.downloadUrl, '_blank')
  } catch (err: any) {
    const errorResponse: ErrorResponse = {
      error: err.message || 'Export failed',
      details: err.details,
      errorType: err.errorType || 'server',
      isRecoverable: err.isRecoverable ?? true
    }

    emit('error', errorResponse)

    console.error('[Min8tEditor] Export failed:', err)

    alert(`Export failed: ${err.message}`)
  }
}

/**
 * ========================
 * LIFECYCLE HOOKS
 * ========================
 */

/**
 * Component mounted - initialize plugin
 */
onMounted(() => {
  console.log('[Min8tEditor] Component mounted, initializing plugin...')
  initPlugin()
})

/**
 * Component unmounted - cleanup plugin
 */
onUnmounted(() => {
  if (pluginInstance) {
    pluginInstance.destroy()
    pluginInstance = null
    console.log('[Min8tEditor] Plugin destroyed')
  }

  emit('destroyed')
})

/**
 * Watch authToken changes and reinitialize
 *
 * If the auth token changes, reinitialize the plugin with the new token.
 */
watch(() => props.authToken, (newToken, oldToken) => {
  if (newToken !== oldToken && pluginInstance) {
    console.log('[Min8tEditor] Auth token changed, reinitializing...')
    pluginInstance.destroy()
    initPlugin()
  }
})
</script>

<style scoped>
/**
 * Component Styles
 *
 * Scoped styles for the min8t editor component.
 */

.min8t-editor-wrapper {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell,
    sans-serif;
}

.min8t-editor-container {
  width: 100%;
  min-height: 600px;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  overflow: hidden;
  background: #ffffff;
}

/* Loading State */
.min8t-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 80px 20px;
  text-align: center;
}

.spinner {
  width: 50px;
  height: 50px;
  border: 4px solid #f3f3f3;
  border-top: 4px solid #3498db;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

.min8t-loading p {
  margin-top: 20px;
  font-size: 16px;
  color: #666;
}

/* Error State */
.min8t-error {
  padding: 40px 20px;
  text-align: center;
  background: #fff5f5;
  border: 1px solid #fc8181;
  border-radius: 8px;
  margin: 20px 0;
}

.min8t-error h3 {
  color: #c53030;
  margin-bottom: 10px;
}

.min8t-error p {
  color: #742a2a;
  margin: 8px 0;
}

.error-details {
  font-size: 14px;
  color: #9b2c2c;
  font-family: monospace;
  background: #fff;
  padding: 10px;
  border-radius: 4px;
  margin-top: 10px;
  max-width: 600px;
  margin-left: auto;
  margin-right: auto;
  overflow-x: auto;
}

.retry-button {
  margin-top: 20px;
  padding: 10px 24px;
  background: #3182ce;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 14px;
  cursor: pointer;
  transition: background 0.2s;
}

.retry-button:hover {
  background: #2c5282;
}

/* Action Buttons */
.min8t-actions {
  display: flex;
  gap: 12px;
  margin-top: 20px;
  flex-wrap: wrap;
}

.action-button {
  padding: 10px 20px;
  background: #3182ce;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s, transform 0.1s;
}

.action-button:hover:not(:disabled) {
  background: #2c5282;
  transform: translateY(-1px);
}

.action-button:active:not(:disabled) {
  transform: translateY(0);
}

.action-button:disabled {
  background: #a0aec0;
  cursor: not-allowed;
}

.save-button {
  background: #38a169;
}

.save-button:hover:not(:disabled) {
  background: #2f855a;
}

/* HTML Preview */
.min8t-preview {
  margin-top: 20px;
  padding: 20px;
  background: #f7fafc;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
}

.min8t-preview h3 {
  margin-bottom: 15px;
  color: #2d3748;
}

.min8t-preview pre {
  background: #1a202c;
  color: #e2e8f0;
  padding: 15px;
  border-radius: 4px;
  overflow-x: auto;
  max-height: 400px;
  overflow-y: auto;
}

.min8t-preview code {
  font-family: 'Monaco', 'Courier New', monospace;
  font-size: 13px;
  line-height: 1.5;
}

.close-preview {
  margin-top: 10px;
  padding: 8px 16px;
  background: #718096;
  color: white;
  border: none;
  border-radius: 4px;
  font-size: 13px;
  cursor: pointer;
}

.close-preview:hover {
  background: #4a5568;
}

/* Responsive Design */
@media (max-width: 768px) {
  .min8t-actions {
    flex-direction: column;
  }

  .action-button {
    width: 100%;
  }
}
</style>
